### ISSUE TITLE
Runtime dependency

### ISSUE THREAD

**Issue by jinjingfarm** [j-easy/easy-jobs#11]
What is the easy-jobs runtime dependency? It seems that the server has its own main(), therefore, there is no dependency of, for example, netty http lib？

**Comment by benas** [comment]
Hi Mike,

Runtime dependencies can be found in the `lib` directory of the distribution.
The job server also requires the jdbc driver of your database of choice which can be found in the `drivers` folder of the distribution.

You can find more details in the wiki: https://github.com/j-easy/easy-jobs/wiki/getting-started#download-distribution

Kr
Mahmoud

**Comment by jinjingfarm** [comment]
Thanks for the info
