### ISSUE TITLE
Provide a pre-configured workspace for insomnia rest client

### ISSUE THREAD

**Issue by benas** [j-easy/easy-jobs#12]
The idea is to help lazy people (like me!) to get started quickly playing around with Easy Jobs through its REST API.

This issue provides a pre-configured workspace with all endpoints for [insomnia](https://insomnia.rest/) rest client:

![easy-jobs-insomnia](https://user-images.githubusercontent.com/1210553/27677978-cfa6f1f8-5cb3-11e7-9e0f-84160d7fd50e.png)

Download the workspace here:

[Easy-Jobs-v0.2_insomnia_workspace.zip](https://github.com/j-easy/easy-jobs/files/1111318/Easy-Jobs-v0.2_insomnia_workspace.zip)

You can then import it through insomnia's wizard.

**Comment by nabilov** [comment]
i'm using postman :)

**Comment by benas** [comment]
Here it is : #13 😄

**Comment by nabilov** [comment]
Thanks ! :)
